on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: supperthomas/hello-world-docker-action@v6
        with:
          who-to-greet: 'Mona the Octocat' 
